# Generated by Django 5.0.6 on 2024-05-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Add the name of the Font Awesome icon', max_length=200)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
    ]
