# Generated by Django 5.0.6 on 2024-06-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='default_price',
            field=models.IntegerField(),
        ),
    ]
