# Generated by Django 5.0.6 on 2024-06-04 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_category'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_reminder',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='expiry_date',
            new_name='reminder_date',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='paymentmethod',
            new_name='reminder_notes',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_categorys', to='services.category'),
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
