# Generated by Django 5.0.6 on 2024-06-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_remove_subscription_subscription_reminder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_name',
            field=models.CharField(default='default_name', max_length=100),
            preserve_default=False,
        ),
    ]
